
package cadastrousuario;

import Modelo.Pessoa;
import Requisicao.HttpRequisicao;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emerson Borges Ferreira
 *  Eng. Computação
 * 
 */
public class TelaListarUsuarios extends javax.swing.JFrame {
    
    TelaExcluirUsuario objExcluir;
    TelaEditarUsuario objEditar;
    ArrayList<Integer> idsTabela = new ArrayList<Integer>(); 
    List<Pessoa> listaPessoa;
    
    /**
     * Creates new form TelaListarUsuarios
     */
    public TelaListarUsuarios() {
        
        initComponents();
        
        ler_JTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        btnCancelarLista = new javax.swing.JButton();
        btnExcluirLista = new javax.swing.JButton();
        btnEditarLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesquisa Usuários");
        setResizable(false);

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "Login", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLista);

        btnCancelarLista.setText("Fechar");
        btnCancelarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarListaActionPerformed(evt);
            }
        });

        btnExcluirLista.setText("Excluir");
        btnExcluirLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirListaActionPerformed(evt);
            }
        });

        btnEditarLista.setText("Editar");
        btnEditarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarListaActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione um usuário na lista, e escolha uma das opções. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(btnEditarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirLista, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarLista)
                    .addComponent(btnExcluirLista)
                    .addComponent(btnEditarLista)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa_usuario72.png"))); // NOI18N

        jLabel2.setText("Usuários Cadastrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarListaActionPerformed
        // TODO add your handling code here:
         dispose(); // Fecha Janela
    }//GEN-LAST:event_btnCancelarListaActionPerformed

    private void btnExcluirListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirListaActionPerformed
        // TODO add your handling code here:

        if( jTableLista.getSelectedRow() != -1 ) {
            if(objExcluir == null){
               objExcluir = new TelaExcluirUsuario(); 
               objExcluir.setVisible(true);
               objExcluir.recebeUsuarioParaExcluir( listaPessoa.get( idsTabela.get(jTableLista.getSelectedRow())) );
               dispose();
            }else{
                objExcluir.setVisible(true);
                objExcluir.setState(TelaExcluirUsuario.NORMAL);
                objExcluir.recebeUsuarioParaExcluir( listaPessoa.get( idsTabela.get(jTableLista.getSelectedRow())) );
                dispose();
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um usuário!");
        }
    }//GEN-LAST:event_btnExcluirListaActionPerformed

    private void btnEditarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarListaActionPerformed
        // TODO add your handling code here:

         if( jTableLista.getSelectedRow() != -1 ) {
            if(objEditar == null){
               objEditar = new TelaEditarUsuario(); 
               objEditar.setVisible(true);
               objEditar.recebeUsuarioParaEditar( listaPessoa.get( idsTabela.get(jTableLista.getSelectedRow())) );
               dispose();
            }else{
                objEditar.setVisible(true);
                objEditar.setState(TelaExcluirUsuario.NORMAL);
                objEditar.recebeUsuarioParaEditar( listaPessoa.get( idsTabela.get(jTableLista.getSelectedRow())) );
                dispose();
            }   
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um usuário!");
        }
        
        
    }//GEN-LAST:event_btnEditarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarUsuarios().setVisible(true);
                
            }
        });
    }
    
    
    public void ler_JTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableLista.getModel();
        modelo.setNumRows(0); // Evitar repetição das linhas
    
        HttpRequisicao req = new HttpRequisicao();
        Gson g = new Gson();
 
        try{
            String jsonResp = req.sendGet("getPessoasInJSON");

            java.lang.reflect.Type ListPessoaType = new TypeToken<List<Pessoa>>(){}.getType();
            listaPessoa = g.fromJson(jsonResp, ListPessoaType);

            for(int i=0;i<listaPessoa.size();i++){

                modelo.addRow(new Object[]{
                    listaPessoa.get(i).getNome(),
                    listaPessoa.get(i).getSobreNome(),
                    listaPessoa.get(i).getLogin(),
                    listaPessoa.get(i).getEmail()
                });
                idsTabela.add(i);
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao buscar usuários!" );
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLista;
    private javax.swing.JButton btnEditarLista;
    private javax.swing.JButton btnExcluirLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    // End of variables declaration//GEN-END:variables
}
